sudo: false
language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn cache clean
  - yarn install --production --ignore-scripts --prefer-offline
  - yarn global add jest-cli
